- name: Install common used software
  ansible.builtin.apt:
    update_cache: true
    name:
      - lsb-release
      - vim
      - flatpak
      - distrobox
    state: present
  become: true

- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.jetbrains.PyCharm-Professional
      - com.jetbrains.WebStorm
    state: present
    method: system
  become: true
