- name: Install common used software
  community.general.zypper:
    update_cache: true
    name:
      - vim
      - sshpass
      - rsync
      - flatpak
    state: present
  become: true

- name: Install wsl patterns
  community.general.zypper:
    update_cache: true
    name:
      - wsl_base
      - wsl_systemd
      - wsl_gui
    state: present
    type: pattern
  become: true

- name: Register flathub
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present
  become: true


- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.getpostman.Postman
      - com.github.tchx84.Flatseal
      - com.jetbrains.WebStorm
      - com.jetbrains.PyCharm-Professional
    remote: flathub
    state: present
    method: system
  become: true
