- name: Setup wsl
  hosts: wsl
  connection: local
  vars_files:
    - vars.yml
  vars_prompt:
    - name: git_user
      prompt: Enter git username
      private: false
    - name: git_email
      prompt: Enter git email
      private: false
    - name: wsl_version
      prompt: Enter WSL version
      private: false
  roles:
    - software
    - zsh
    - git
    - role: docker
      when: wsl_version == "2"
    - ssh
    - aws
    - wsl_config
