- name: Setup wsl
  hosts: wsl
  connection: local
  vars_files:
    - vars.yml
  vars_prompt:
    - name: git_user
      prompt: Enter git username
      private: false
    - name: git_email
      prompt: Enter git email
      private: false
    - name: npiperelay_path
      prompt: npiperelay executable path
      private: false
  roles:
    - software
    - zsh
    - git
    - jetbrains
    - docker
    - ssh
    - aws
    - wsl_config
