- name: Install appimage dependencies
  community.general.zypper:
    update_cache: true
    name:
      - tar
      - libfuse2
      - fontconfig
      - libgtk-3-0
      - Mesa
      - libXi6
      - libXrender1
      - libXtst6
      - fuse
      - libgthread-2_0-0
    state: present
  become: true
