- name: Ensure local bin folder
  ansible.builtin.file:
    path: ~/.local/bin/
    state: directory
    mode: "{{ user_dir_perm }}"

- name: Ensure .ssh folder
  ansible.builtin.file:
    path: ~/.ssh/
    state: directory
    mode: "700"

- name: Copy ssh files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.ssh/
    force: false
    mode: "{{ user_file_perm }}"
  with_fileglob: "files/.ssh/*"

- name: Set correct ssh file permissions
  ansible.builtin.shell:
    cmd: |
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/*
      chmod 644 ~/.ssh/*.pub || true
    executable: /bin/bash
  changed_when: false

- name: Update zshrc
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
    state: present
  loop:
    - { key: "export SSH_AUTH_SOCK", value: "/mnt/d/Programs/ssh-agent/ssh-agent.sock" }
