- name: Install zsh
  community.general.zypper:
    update_cache: true
    name:
      - zsh
      - git
      - gcc
      - automake
      - bzip2
      - libbz2-devel
      - xz
      - xz-devel
      - openssl-devel
      - ncurses-devel
      - readline-devel
      - zlib-devel
      - tk-devel
      - libffi-devel
      - sqlite3-devel
      - gdbm-devel
      - make
      - findutils
      - patch
  become: true

- name: Install antigen
  ansible.builtin.git:
    repo: https://github.com/zsh-users/antigen.git
    dest: ~/antigen
    version: master

- name: Copy zshrc
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/xLasercut/my-zsh/master/.zshrc
    dest: ~/.zshrc
    mode: "{{ user_file_perm }}"

- name: Copy p10k config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/xLasercut/my-zsh/master/.p10k.zsh
    dest: ~/.p10k.zsh
    mode: "{{ user_file_perm }}"

- name: Set login shell to `/bin/zsh` with `usermod` for user {{ ansible_user }}
  ansible.builtin.command: usermod --shell /bin/zsh {{ ansible_user }}
  changed_when: false
  become: true

- name: Initialise zsh plugins
  ansible.builtin.shell:
    cmd: /bin/zsh ~/.zshrc
    executable: /bin/bash
  changed_when: false
