- name: Install docker
  community.general.zypper:
    update_cache: true
    name:
      - docker
      - docker-compose
      - docker-compose-switch
    state: present
  become: true

- name: Add user to docker
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
    state: present
  become: true

- name: Start service
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true
  become: true
